Bot_Token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
SecondTokens: ['XXXXXXXXXXXXXX','XXXXXXXXXXXXXXX']
Custom_Status: "XXXXXXX"
GuildID: "XXXXXXXXXXXXXXXXXX"
Log_Channel: "XXXXXXXXXXXXXXXXXX"
Whitelist_Members: ['XXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXX'] 